insert into ingredients values (33, 'onions');
insert into ingredients values (34, 'butter');
insert into ingredients values (35, 'chicken');
insert into ingredients values (36, 'salmon');
insert into ingredients values (37, 'garlic');
insert into ingredients values (38, 'dijon mustard');
insert into ingredients values (39, 'salt');
insert into ingredients values (40, 'ham');
insert into ingredients values (41, 'rice');
insert into ingredients values (42, 'water');
insert into receipe values (36, 'http://www.kraftfoods.com/kf/recipes/ garlic-dijon-grilling-sauce-56449.aspx', 'garlic', 1, 'http://img.recipepuppy.com/ 631164.jpg', 'Garlic Dijon Grilling Sauce');
insert into receipe values (2, 'http://www.grouprecipes.com/43522/creamyscrambled-eggs-recipe.html', 'onions', 1, 'http://img.recipepuppy.com/ 373064.jpg', 'Creamy Scrambled Eggs Recipe Recipe');
insert into receipe values (4, 'http://www.eatingwell.com/recipes/ spaghetti_clams_corn.html', 'onions', 1, 'http://img.recipepuppy.com/ 698569.jpg', 'Spaghetti with Clams & Corn');
insert into receipe values (5, 'http://www.grouprecipes.com/43522/creamyscrambled-eggs-recipe.html', 'onions', 1, 'http://img.recipepuppy.com/ 373064.jpg', 'Creamy Scrambled Eggs Recipe Recipe');
insert into receipe values (6, 'http://www.eatingwell.com/recipes/ meatloaf.html', 'onions', 1, 'http://img.recipepuppy.com/ 707237.jpg', 'Green Bean Casserole');
insert into receipe values (10, 'http://www.recipezaar.com/Crock-PotCaramelized-Onions-191625', 'butter', 1, 'http://img.recipepuppy.com/ 338845.jpg', 'Crock Pot Caramelized Onions');
insert into receipe values (13, 'http://www.recipezaar.com/Pulled-ChickenSandwiches-Crock-Pot-24254', 'chicken', 1, 'http://img.recipepuppy.com/ 107122.jpg', 'Pulled Chicken Sandwiches (Crock Pot)');
insert into receipe values (16, 'http://www.recipezaar.com/GrilledChipotle-Salmon-With-Pineapple-Cilantro-Rice-12856', 'salmon', 1, 'http://img.recipepuppy.com/ 715159.jpg', 'Grilled Chipotle Salmon With Pineapple Cilantro Rice');
insert into receipe values (19, 'http://allrecipes.com/Recipe/RoastChicken-with-Rosemary/Detail.aspx', 'salt', 1, 'http://img.recipepuppy.com/18294.jpg', 'Roast Chicken with Rosemary');
insert into receipe values (21, 'http://www.recipezaar.com/Fresh-VegetableSpring-Rolls-12911', 'ham', 1, 'http://img.recipepuppy.com/ 581601.jpg', 'Fresh Vegetable Spring Rolls');
insert into receipe values (23, 'http://www.recipezaar.com/Chicken-SaladWith-Rice-Noodles-25092', 'rice', 1, 'http://img.recipepuppy.com/ 298452.jpg', 'Chicken Salad With Rice Noodles');
insert into receipe values (29, 'http://www.nibbledish.com/people/ wokkingmum/recipes/rice-sandwich', 'rice', 1, 'http://img.recipepuppy.com/ 516214.jpg', 'Rice sandwich');
insert into receipe values (32, 'http://www.eatingwell.com/recipes/ zucchini_rice_casserole.html', 'rice', 1, 'http://img.recipepuppy.com/ 697402.jpg', 'Zucchini Rice Casserole');
insert into receipe_ingredients values (2, 33);
insert into receipe_ingredients values (4, 33);
insert into receipe_ingredients values (5, 33);
insert into receipe_ingredients values (6, 33);
insert into receipe_ingredients values (10, 34);
insert into receipe_ingredients values (13, 35);
insert into receipe_ingredients values (16, 36);
insert into receipe_ingredients values (19, 37);
insert into receipe_ingredients values (21, 38);
insert into receipe_ingredients values (23, 39);
insert into receipe_ingredients values (29, 39);
insert into receipe_ingredients values (32, 39);
insert into receipe_ingredients values (36, 40);